name: Docker-publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  docker-public:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_USERNAME

      - name: Build the Docker image
        run: docker build . -t mrdarkson/devops-lab:${{ github.sha }}

      - name: Docker push
        run: docker push mrdarkson/devops-lab:${{ github.sha }}
