name: Lint
on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}