name: Release Workflow

on:
  push:
    tags:
      - v*
    

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set u
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
       mvn clean install
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: target/*.jar
